name: misspell

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: sobolevn/misspell-fixer-action@master
    - uses: peter-evans/create-pull-request@v3.10.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 'Typos fix by misspell-fixer'
